# Generated by Django 5.0.4 on 2024-04-29 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diet",
            fields=[
                ("diet_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "Diet",
            },
        ),
        migrations.CreateModel(
            name="Nutrition",
            fields=[
                (
                    "nutrition_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("vitamins", models.JSONField(default=dict)),
                ("minerals", models.JSONField(default=dict)),
                ("amino_acids", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "Nutrition",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=60)),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("weight", models.FloatField()),
                ("body_fat", models.FloatField()),
                ("role", models.SmallIntegerField(default=0)),
                ("date_of_birth", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "User",
            },
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "meal_plan_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "time",
                    models.SmallIntegerField(
                        choices=[
                            (0, "breakfast"),
                            (1, "lunch"),
                            (2, "snack"),
                            (3, "dinner"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "fk_diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.diet"
                    ),
                ),
            ],
            options={
                "db_table": "MealPlan",
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                ("food_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
                ("description", models.TextField()),
                ("carbs", models.FloatField()),
                ("protein", models.FloatField()),
                ("fat", models.FloatField()),
                ("calories", models.FloatField()),
                (
                    "fk_nutrition",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.nutrition",
                    ),
                ),
            ],
            options={
                "db_table": "Food",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "submission_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("note", models.TextField()),
                ("reviewer", models.CharField(blank=True, max_length=16, null=True)),
                ("is_accepted", models.BooleanField(default=False)),
                (
                    "fk_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
            options={
                "db_table": "Submission",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("preferences", models.JSONField(default=dict)),
                (
                    "fk_diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.diet"
                    ),
                ),
                (
                    "fk_nutrition",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.nutrition",
                    ),
                ),
                (
                    "fk_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
            options={
                "db_table": "Profile",
            },
        ),
    ]
