# Generated by Django 5.0.4 on 2024-05-01 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_body_fat_alter_user_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="fk_diet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.diet",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fk_nutrition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.nutrition",
            ),
        ),
    ]
