# Generated by Django 5.0.4 on 2024-05-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_profile_fk_diet_alter_profile_fk_nutrition"),
    ]

    operations = [
        migrations.AddField(
            model_name="diet",
            name="photo_url",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="food",
            name="photo_url",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
