# Generated by Django 5.0.4 on 2024-05-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_diet_photo_url_food_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="foods",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
