# Generated by Django 5.0.4 on 2024-05-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_mealplan_foods"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blood_pressure",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="heart_rate",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="oxygen_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
